name: Deploy
on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CI: true
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    #needs: build_and_push

    steps:
      - name: Redeploy beanstalk
        run: aws elasticbeanstalk update-environment --application-name app-sellaci --environment-name app-env-sellaci --version-label latest --region eu-central-1
